name: ci
on:
  push:
    branches:
      - deploy
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install --user --no-warn-script-location --disable-pip-version-check -U git+https://${GH_TOKEN}@github.com/photoprism/mkdocs-material-insiders.git
      - run: pip install --user --no-warn-script-location --disable-pip-version-check -U -r requirements.txt
      - run: mkdocs gh-deploy --force --config-file mkdocs.deploy.yml
